apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  db_endpoint: {{ .Values.secrets.database_endpoint | b64enc }}
  db_username: {{ .Values.secrets.database_username | b64enc }}
  db_password: {{ .Values.secrets.database_password | b64enc }}